import os
os.makedirs("src/coding_agent", exist_ok=True)

# contracts.py
f = open("src/coding_agent/contracts.py", "w")
f.write("from __future__ import annotations\n")
f.write("from datetime import datetime\n")
f.write("from typing import Literal, Optional\n")
f.write("from pydantic import BaseModel, Field\n\n")
f.write("class ImplementationPlan(BaseModel):\n")
f.write("    approach: str\n")
f.write("    steps: list[str]\n")
f.write("    libraries: list[str]\n")
f.write("    edge_cases: list[str]\n")
f.write("    validation_criteria: str\n")
f.write("    complexity: Literal[\"low\", \"medium\", \"high\"]\n")
f.write("    estimated_tokens: int\n\n")
f.write("class GeneratedCode(BaseModel):\n")
f.write("    code: str\n")
f.write("    language: str = \"python\"\n")
f.write("    files: dict[str, str] = {}\n")
f.write("    imports: list[str] = []\n")
f.write("    has_docstrings: bool = False\n")
f.write("    has_type_hints: bool = False\n")
f.write("    entry_point: str = \"\"\n\n")
f.write("class ReviewIssue(BaseModel):\n")
f.write("    severity: Literal[\"critical\", \"major\", \"minor\", \"info\"]\n")
f.write("    category: str\n")
f.write("    message: str\n")
f.write("    line: int | None = None\n")
f.write("    fix_suggestion: str | None = None\n\n")
f.write("class SecurityIssue(BaseModel):\n")
f.write("    severity: Literal[\"critical\", \"high\", \"medium\", \"low\"]\n")
f.write("    cwe_id: str | None = None\n")
f.write("    description: str\n")
f.write("    line: int | None = None\n")
f.write("    remediation: str = \"\"\n\n")
f.write("class PerformanceIssue(BaseModel):\n")
f.write("    severity: Literal[\"major\", \"minor\", \"info\"]\n")
f.write("    description: str\n")
f.write("    line: int | None = None\n")
f.write("    suggestion: str = \"\"\n\n")
f.write("class StyleViolation(BaseModel):\n")
f.write("    tool: Literal[\"ruff\", \"mypy\", \"bandit\", \"custom\"]\n")
f.write("    code: str\n")
f.write("    message: str\n")
f.write("    line: int\n")
f.write("    column: int = 0\n\n")
f.write("class ReviewResult(BaseModel):\n")
f.write("    passed: bool\n")
f.write("    quality_score: int = 0\n")
f.write("    issues: list = []\n")
f.write("    suggestions: list[str] = []\n")
f.write("    security_issues: list = []\n")
f.write("    performance_issues: list = []\n")
f.write("    style_violations: list = []\n\n")
f.write("class FailedTest(BaseModel):\n")
f.write("    name: str\n")
f.write("    error: str\n")
f.write("    traceback: str = \"\"\n\n")
f.write("class TestResult(BaseModel):\n")
f.write("    passed: int = 0\n")
f.write("    failed: int = 0\n")
f.write("    skipped: int = 0\n")
f.write("    coverage_percent: float = 0.0\n")
f.write("    execution_time_ms: int = 0\n")
f.write("    test_output: str = \"\"\n")
f.write("    failed_tests: list = []\n")
f.write("    all_passed: bool = False\n")
print("contracts.py written")