f = open("tests/unit/test_config.py", "w")
f.write("import pytest\n")
f.write("from coding_agent.config import Config\n\n")
f.write("def test_config_loads_from_defaults():\n")
f.write("    config = Config()\n")
f.write("    assert config.environment == \"development\"\n\n")
f.write("def test_config_loads_providers_from_yaml():\n")
f.write("    config = Config()\n")
f.write("    assert len(config.llm.providers) > 0\n\n")
f.write("def test_config_env_override(monkeypatch):\n")
f.write("    monkeypatch.setenv(\"LOG_LEVEL\", \"DEBUG\")\n")
f.write("    config = Config()\n")
f.write("    assert config.log_level == \"DEBUG\"\n")
f.close()
print("test_config.py written")