# state_store.py
f = open("src/coding_agent/state_store.py", "w")
f.write("from __future__ import annotations\n")
f.write("from typing import Optional\n")
f.write("from .state import SharedState\n\n")
f.write("class StateStore:\n")
f.write("    def __init__(self):\n")
f.write("        self._states: dict[str, SharedState] = {}\n\n")
f.write("    async def save(self, state: SharedState):\n")
f.write("        self._states[state.request_id] = state\n\n")
f.write("    async def get(self, request_id: str) -> Optional[SharedState]:\n")
f.write("        return self._states.get(request_id)\n\n")
f.write("    async def delete(self, request_id: str):\n")
f.write("        self._states.pop(request_id, None)\n\n")
f.write("    async def list_ids(self) -> list[str]:\n")
f.write("        return list(self._states.keys())\n")
print("state_store.py written")