# schemas.py
f = open("src/coding_agent/schemas.py", "w")
f.write("from __future__ import annotations\n")
f.write("from datetime import datetime\n")
f.write("from typing import Literal, Optional\n")
f.write("from pydantic import BaseModel, Field\n")
f.write("from .contracts import ImplementationPlan, GeneratedCode, ReviewResult, TestResult\n\n")
f.write("class GenerationOptions(BaseModel):\n")
f.write("    max_tokens: int = 4000\n")
f.write("    temperature: float = 0.3\n")
f.write("    quality_threshold: int = 70\n")
f.write("    run_tests: bool = True\n")
f.write("    timeout_seconds: int = 60\n\n")
f.write("class GenerationRequest(BaseModel):\n")
f.write("    user_request: str = Field(..., min_length=1, max_length=10000)\n")
f.write("    context: Optional[str] = None\n")
f.write("    constraints: Optional[dict] = None\n")
f.write("    language: str = \"python\"\n")
f.write("    options: GenerationOptions = GenerationOptions()\n\n")
f.write("class GenerationMetadata(BaseModel):\n")
f.write("    request_id: str = \"\"\n")
f.write("    started_at: datetime = Field(default_factory=datetime.utcnow)\n")
f.write("    completed_at: Optional[datetime] = None\n")
f.write("    total_latency_ms: float = 0.0\n")
f.write("    total_tokens: int = 0\n")
f.write("    total_cost_usd: float = 0.0\n")
f.write("    agent_latencies: dict[str, float] = {}\n")
f.write("    llm_calls: int = 0\n")
f.write("    provider_used: str = \"\"\n")
f.write("    model_used: str = \"\"\n\n")
f.write("class GenerationResult(BaseModel):\n")
f.write("    status: Literal[\"success\", \"partial\", \"failed\"]\n")
f.write("    request_id: str\n")
f.write("    user_request: str\n")
f.write("    plan: Optional[ImplementationPlan] = None\n")
f.write("    code: Optional[GeneratedCode] = None\n")
f.write("    review: Optional[ReviewResult] = None\n")
f.write("    tests: Optional[TestResult] = None\n")
f.write("    metadata: GenerationMetadata = GenerationMetadata()\n")
f.write("    errors: list[str] = []\n")
print("schemas.py written")