# errors.py
f = open("src/coding_agent/errors.py", "w")
f.write("class CodingAgentError(Exception):\n")
f.write("    def __init__(self, message: str, recoverable: bool = False):\n")
f.write("        self.recoverable = recoverable\n")
f.write("        super().__init__(message)\n\n")
f.write("class AgentError(CodingAgentError):\n")
f.write("    def __init__(self, agent_name: str, message: str, recoverable: bool = True):\n")
f.write("        self.agent_name = agent_name\n")
f.write("        super().__init__(f\"[{agent_name}] {message}\", recoverable)\n\n")
f.write("class LLMProviderError(CodingAgentError):\n")
f.write("    def __init__(self, provider: str, message: str, retry_after: int | None = None):\n")
f.write("        self.provider = provider\n")
f.write("        self.retry_after = retry_after\n")
f.write("        super().__init__(f\"[{provider}] {message}\", recoverable=True)\n\n")
f.write("class SandboxError(CodingAgentError):\n")
f.write("    def __init__(self, error_type: str, message: str):\n")
f.write("        self.error_type = error_type\n")
f.write("        super().__init__(f\"[{error_type}] {message}\", recoverable=False)\n\n")
f.write("class ConfigError(CodingAgentError):\n")
f.write("    def __init__(self, message: str):\n")
f.write("        super().__init__(message, recoverable=False)\n")
print("errors.py written")