# state.py
f = open("src/coding_agent/state.py", "w")
f.write("from __future__ import annotations\n")
f.write("from datetime import datetime\n")
f.write("from typing import Optional\n")
f.write("from pydantic import BaseModel, Field\n")
f.write("from .contracts import ImplementationPlan, GeneratedCode, ReviewResult, TestResult\n\n")
f.write("class SharedState(BaseModel):\n")
f.write("    request_id: str\n")
f.write("    user_request: str\n")
f.write("    plan: Optional[ImplementationPlan] = None\n")
f.write("    code: Optional[GeneratedCode] = None\n")
f.write("    review: Optional[ReviewResult] = None\n")
f.write("    tests: Optional[TestResult] = None\n")
f.write("    metadata: dict = {}\n")
f.write("    created_at: datetime = Field(default_factory=datetime.utcnow)\n")
f.write("    updated_at: datetime = Field(default_factory=datetime.utcnow)\n\n")
f.write("    def update_plan(self, plan):\n")
f.write("        self.plan = plan\n")
f.write("        self.updated_at = __import__(\"datetime\").datetime.utcnow()\n\n")
f.write("    def update_code(self, code):\n")
f.write("        self.code = code\n")
f.write("        self.updated_at = __import__(\"datetime\").datetime.utcnow()\n\n")
f.write("    def update_review(self, review):\n")
f.write("        self.review = review\n")
f.write("        self.updated_at = __import__(\"datetime\").datetime.utcnow()\n\n")
f.write("    def update_tests(self, tests):\n")
f.write("        self.tests = tests\n")
f.write("        self.updated_at = __import__(\"datetime\").datetime.utcnow()\n")
print("state.py written")