f = open("tests/conftest.py", "w")
f.write("import pytest\n")
f.write("import sys\n")
f.write("import os\n")
f.write("sys.path.insert(0, os.path.join(os.path.dirname(__file__), \"..\", \"src\"))\n\n")
f.write("@pytest.fixture\n")
f.write("def mock_llm_response():\n")
f.write("    from coding_agent.llm.models import LLMResponse, TokenUsage\n")
f.write("    return LLMResponse(\n")
f.write("        content=\"{\\\"approach\\\": \\\"test\\\", \\\"steps\\\": [\\\"step1\\\"], \\\"libraries\\\": [], \\\"edge_cases\\\": [], \\\"validation_criteria\\\": \\\"test\\\", \\\"complexity\\\": \\\"low\\\", \\\"estimated_tokens\\\": 100}\",\n")
f.write("        usage=TokenUsage(prompt_tokens=50, completion_tokens=50, total_tokens=100),\n")
f.write("        model=\"test-model\",\n")
f.write("        finish_reason=\"stop\",\n")
f.write("        latency_ms=100,\n")
f.write("    )\n\n")
f.write("@pytest.fixture\n")
f.write("def mock_llm_provider(mock_llm_response):\n")
f.write("    from unittest.mock import AsyncMock\n")
f.write("    from coding_agent.llm.base import LLMProvider\n")
f.write("    provider = AsyncMock(spec=LLMProvider)\n")
f.write("    provider.generate.return_value = mock_llm_response\n")
f.write("    provider.name = \"test\"\n")
f.write("    provider.models = [\"test-model\"]\n")
f.write("    provider.health_check = AsyncMock(return_value=True)\n")
f.write("    provider.estimate_cost.return_value = 0.001\n")
f.write("    return provider\n")
f.close()
print("conftest.py written")